//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSLS.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Book
    {
        public Book()
        {
            this.Borrow = new HashSet<Borrow>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "请输入图书编码")]
        public string Code { get; set; }
        [Required(ErrorMessage = "请输入图书名称")]
        public string Name { get; set; }
         [Required(ErrorMessage = "请输入作者名称")]
        public string Authors { get; set; }
        [Required(ErrorMessage = "请输入出版社")]
        public string Press { get; set; }
        public string ImageUrl { get; set; }
        [Required(ErrorMessage = "请输入简介")]
        public string Description { get; set; }
         [Required(ErrorMessage = "请输入出版日期")]
        public Nullable<System.DateTime> PublishDate { get; set; }
        [Required]
        [Range(0.01, double.MaxValue, ErrorMessage = "图书价格必须大于0")]
        public Nullable<decimal> Price { get; set; }
        public string Status { get; set; }
        public int Category_ID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Borrow> Borrow { get; set; }
    }
}
